### ISSUE TITLE
Remove else statements when a default is available

### ISSUE THREAD

**Issue by SpecialDragonfly** [fullcircle7/Shop#1]
https://github.com/fullcircle7/Shop/blob/master/lib/shop_project/Run.php#L53

`if (somethingThatIsTrue) {`
`$value="hello";`
`} else {`
`$value="world";`
`}`

Should be rewritten:
`$value="world";`
`if (somethingThatIsTrue){`
`$value="hello";`
`}`

This neatly sets up the default value and reduces the number of paths through the code.

**Comment by fullcircle7** [comment]
I have rewritten these as suggested.

Also, I have removed the assignment of the $result variable from the functions themselves and put them at the top of the class and referenced it using $this->

This is instead of writing "$result = 'The request failed';" 3 times, it's now only written once.
