### ISSUE TITLE
Modify goodsIn/goodsOut methods in Transaction

### ISSUE THREAD

**Issue by SpecialDragonfly** [fullcircle7/Shop#3]
The steps to increasing the amount of an item are, at the simplest:
1. Create a goods-in transaction

However, that should be broken down into
1. Create a transaction `$t = new Transaction`
2. Tell it that it's a goods in transaction `$t->goodsIn(values)`
because that way a transaction can be made to do many things, without the chance of it messing up existing code.

The above can be further broken down by saying, "A transaction needs to know about the database to which it is saving." Thus point 1 above becomes:
1.1 Create a DB object `$db = new DB() // DB name needs to be whatever your DB class is called.` 
1.2 Create a Transaction Object `new Transaction($db)`
1.3 As point 2 above.

**Comment by fullcircle7** [comment]
Changes made and new commit done.
