### ISSUE TITLE
Pass DB into Shop Constructor

### ISSUE THREAD

**Issue by SpecialDragonfly** [fullcircle7/Shop#4]
The shop constructor currently takes the action that you wish to do, which is odd for a shop when you think about it. Normally when you go into a shop you're there to browse or to buy, but you don't know that until you enter the shop.
1. Create a 'handle' function in the Shop class. The handle function looks exactly the same as your existing '__construct' method. 
2. Create a new '__construct' method for the Shop class. This should take in a DbAbstract argument.
3. At the bottom of your script, construct the DbAbstract class you're going to use and pass it in as a parameter to the shop constructor.
4. Don't forget to now call '$shop->handle($action);'

The overall objective is to remove the following from the code:
$db = new $dbType;

**Comment by fullcircle7** [comment]
This has been implemented.
