### ISSUE TITLE
Research extending Symfony/Component/Console/Application

### ISSUE THREAD

**Issue by SpecialDragonfly** [fullcircle7/Shop#8]
As all the commands require the Shop class, extending the Application and adding the Shop as a constructor argument might be an option.
The shop is then available within the command classes as:
$this->getApplication()->getShop();

**Comment by fullcircle7** [comment]
I have refactored my code to implement this really good suggestion. I had to add "parent::__construct();" in my new 'ShopApplication' class in order to successfully override the built in constructor class, which I didn't realise at first.
